apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api-micro
  name: api-micro
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
    nodePort: 30500
  selector:
    app: api-micro
status:
  loadBalancer: {}
