apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api-store
  name: api-store
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: api-store
status:
  loadBalancer: {}
